version: "3.8"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    cpu_count: 2
    mem_limit: 512m
    restart: unless-stopped
